import { createCssCompiler } from '../src/cssCompiler.js'
import { createClassUtils } from '../src/class-utils/index.js'
import { theme } from '../src/theme/index.js'
import { createCssFile } from '../src/cssFile.js'

let tabSize = 4
let compiler = createCssCompiler(createClassUtils(), theme, { tabSize })

test('create cssFile instance', () => {
  const cssFile = createCssFile('test/dogtail.test.css', theme, compiler)
  const result = cssFile.render()

  expect(result).toEqual(
    `/* dogtailcss autogenerated file */

@media (min-width: 480px) {
}
@media (min-width: 640px) {
}
@media (min-width: 768px) {
}
@media (min-width: 1024px) {
}
@media (min-width: 1280px) {
}
@media (min-width: 1536px) {
}
`
  )
})

test('compile several screens', () => {
  const cssFile = createCssFile('dogtail.test.css', theme, compiler)
  cssFile.add(
    '1',
    new Set(
      'text-black xs:text-white lg:text-(200,100,100) 2xl:text-maroon'.split(
        /\s+/
      )
    )
  )
  const result = cssFile.render()
  expect(result).toEqual(
    `/* dogtailcss autogenerated file */

.text-black {
    color: #000;
}

@media (min-width: 480px) {
    .xs\\:text-white {
        color: #fff;
    }

}
@media (min-width: 640px) {
}
@media (min-width: 768px) {
}
@media (min-width: 1024px) {
    .lg\\:text-\\(200\\,100\\,100\\) {
        color: rgb(200,100,100);
    }

}
@media (min-width: 1280px) {
}
@media (min-width: 1536px) {
    .\\32 xl\\:text-maroon {
        color: #800000;
    }

}
`
  )
})
